### ISSUE TITLE
метод POST /campaigns/{campaignId}/hidden-offers Управление показом предложений 

### ISSUE THREAD

**Issue by toysforbaby** [yandex-market/yandex-market-php-partner#1]
метод API POST /campaigns/{campaignId}/hidden-offers - Управление показом предложений
нет класса для данного метода, управлять предложениями магазина на Яндекс.Маркете не представляется возможным.

**Comment by MarketLLC** [comment]
Здравствуйте! Ведем разработку данного функционала. В будущем такая возможность появится.

Спасибо за ваш issue!

**Comment by toysforbaby** [comment]
сроки можете подсказать?

**Comment by MarketLLC** [comment]
Ожидаем новую версию в середине-конце декабря.

**Comment by toysforbaby** [comment]
Может вы сможете мне помочь? Запросы на получение информации, сообщить об обновлении прайса работают, но все запросы с передачей параметров приходят с ошибкой "Service responded with error code: "400" and message: "Bad Request"" видимо это POST запросы. например запрос://Установка цен на предложения$priceClient = new \Yandex\Market\Partner\Clients\PriceClient($clientId, $token);$deletePricesResponse = $priceClient->deletePrices($campaignId, ['removeAll' => true]); выдает ошибкуFatal error: Uncaught Yandex\Market\Partner\Exception\PartnerRequestException: Service responded with error code: "400" and message: "Bad Request" in .../YM/src/Yandex/Market/Partner/Clients/Client.php:161 Stack trace: #0 .../YM/src/Yandex/Market/Partner/Clients/PriceClient.php(55): Yandex\Market\Partner\Clients\Client->sendRequest('POST', 'https://api.par...', Array) #1 .../YM/1.php(29): Yandex\Market\Partner\Clients\PriceClient->deletePrices('21069985', Array) #2 {main} thrown in .../YM/src/Yandex/Market/Partner/Clients/Client.php on line 161 предполагаю что ошибка кроется в передаче параметра (['removeAll' => true]) но делается все по вашему образцу.правильно я передаю параметр? пробовал разные вариации...  -- С уважением, интернет-магазин ИГРУШКИ ДЕТЯМ+7 (495) 504-51-45sale@toysforbaby.ruМихаил Иванов   21.11.2018, 15:12, "MarketLLC" <notifications@github.com>:Ожидаем новую версию в середине-конце декабря.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by MarketLLC** [comment]
Здравствуйте! 
 Метод deletePrices не принимает второй параметр, нужно указывать только $campaignId. removeAll => true уже задан в самом методе. 
 Поправим этот момент в документации.

**Comment by toysforbaby** [comment]
Здравствуйте! спасибо. изменения цены тоже не принимает - плохой запрос говорит.какой формат передачи параметра там? -- С уважением, интернет-магазин ИГРУШКИ ДЕТЯМ+7 (495) 504-51-45sale@toysforbaby.ruМихаил Иванов   26.11.2018, 12:11, "MarketLLC" <notifications@github.com>:Здравствуйте!Метод deletePrices не принимает второй параметр, нужно указывать только $campaignId. removeAll => true уже задан в самом методе.Поправим этот момент в документации.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by MarketLLC** [comment]
Не могли бы вы привести пример запроса на изменение цены, на который в ответ приходит ошибка?

**Comment by toysforbaby** [comment]
не помогло ((( $priceClient = new \Yandex\Market\Partner\Clients\PriceClient($clientId, $token);$deletePricesResponse = $priceClient->deletePrices($campaignId); ответ:Fatal error: Uncaught Yandex\Market\Partner\Exception\PartnerRequestException: Service responded with error code: "400" and message: "Bad Request" in .../Yandex/Market/Partner/Clients/Client.php:161 Stack trace: #0 /home/h/htoys/tfb_new/public_html/servise/YM/src/Yandex/Market/Partner/Clients/PriceClient.php(55): Yandex\Market\Partner\Clients\Client->sendRequest('POST', 'https://api.par...', Array) #1 .../YM/1.php(29): Yandex\Market\Partner\Clients\PriceClient->deletePrices('21069985') #2 {main} thrown in .../Yandex/Market/Partner/Clients/Client.php on line 161 может есть режим отладки что бы видеть что передается и приходит? -- С уважением, интернет-магазин ИГРУШКИ ДЕТЯМ+7 (495) 504-51-45sale@toysforbaby.ruФаина Давыдова   26.11.2018, 12:11, "MarketLLC" <notifications@github.com>:Здравствуйте!Метод deletePrices не принимает второй параметр, нужно указывать только $campaignId. removeAll => true уже задан в самом методе.Поправим этот момент в документации.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by MarketLLC** [comment]
Проанализировали ваши запросы и исправили код модуля. Попробуйте загрузить последнюю версию yandex-market-php-partner и сделать запросы заново. 
Спасибо за помощь в обнаружении ошибки!

**Comment by toysforbaby** [comment]
работает!!!!!!

спасибо за оперативное исправление.
с нетерпением ждем управление наличием товаров.

**Comment by toysforbaby** [comment]
возник следующий вопрос: как автоматически обрабатывать ответ API если он "protected", т.е. защищен? В WIKI не нашел инфы.

Yandex\Market\Partner\Models\Response\PostResponse Object
(
    [errors:protected] => 
    [status:protected] => OK
    [result:protected] => 
    [mappingClasses:protected] => Array
        (
            [errors] => Yandex\Market\Partner\Models\Common\Errors
        )

    [propNameMap:protected] => Array
        (
        )

)

**Comment by MarketLLC** [comment]
Для получения данных из ответа используйте функции get(например, getCode(), getMessage() и т.д.). Если вы хотите обрабатывать ошибки, то можете обрабатывать возникающие исключения.

**Comment by MarketLLC** [comment]
Добавлены методы HiddenOffersClient, которые позволяют управлять показом предложений: скрывать и возобновлять показ на Яндекс.Маркете.

**Comment by toysforbaby** [comment]
на запрос$hiddenOffersClient = new \Yandex\Market\Partner\Clients\HiddenOffersClient($clientId, $token);$hideOffersResponse = $hiddenOffersClient->hideOffers($campaignId, [    'hiddenOffers' => [        [            // Идентификатор прайс-листа, обязательный параметр            'feedId' => $feed_id,            // Идентификатор предложения, обязательный параметр                          'offerId' => $id_price_new_offer,            // Количество часов до возобновления показа предложения,            // необязательный параметр                          'ttlInHours' => 26,        ],    ],]); получаем ответ:Yandex\Market\Partner\Models\Response\PostResponse Object
(
    [errors:protected] => 
    [status:protected] => OK
    [result:protected] => 
    [mappingClasses:protected] => Array
        (
            [errors] => Yandex\Market\Partner\Models\Common\Errors
        )

    [propNameMap:protected] => Array
        (
        )

)вроде все работает, но такой ответ при любом $id_price_new_offer, даже том который не существует в прайсе. НО, при проверке скрытых запросом:$hiddenOffersClient = new \Yandex\Market\Partner\Clients\HiddenOffersClient($clientId, $token);$hiddenOffersObject = $hiddenOffersClient->getInfo($feed_id); ошибка:Fatal error: Uncaught Yandex\Common\Exception\ForbiddenException: Access denied in .../YM/src/Yandex/Market/Partner/Clients/Client.php:154 Stack trace: #0 .../YM/src/Yandex/Market/Partner/Clients/HiddenOffersClient.php(28): Yandex\Market\Partner\Clients\Client->sendRequest('GET', 'https://api.par...') #1 .../YM/hide_offers-test.php(15): Yandex\Market\Partner\Clients\HiddenOffersClient->getInfo('340452') #2 {main} thrown in .../YM/src/Yandex/Market/Partner/Clients/Client.php on line 154 становиться не понятно что то скрывается или нет.  29.11.2018, 13:43, "MarketLLC" <notifications@github.com>:Добавлены методы HiddenOffersClient, которые позволяют управлять показом предложений: скрывать и возобновлять показ на Яндекс.Маркете.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by MarketLLC** [comment]
Запрос действительно всегда получает статус OK, ошибки по скрытию содержатся внутри запроса. У себя ошибки с проверкой скрытых предложений не наблюдаем, попробуйте загрузить новую версию библиотеки и повторить запросы.

**Comment by toysforbaby** [comment]
работает.указывали номер прайса а надо было компании.в доках просто число, из-за этого перепутали.  30.11.2018, 20:32, "MarketLLC" <notifications@github.com>:Запрос действительно всегда получает статус OK, ошибки по скрытию содержатся внутри запроса. У себя ошибки с проверкой скрытых предложений не наблюдаем, попробуйте загрузить новую версию библиотеки и повторить запросы.
