### ISSUE TITLE
Метод getModelsOffers не обрабатывает необязательные параметры

### ISSUE THREAD

**Issue by AndreyBobrov** [yandex-market/yandex-market-php-partner#13]
Пытаюсь получить список предложений для списка моделей $modelClient->getModelsOffers(), выяснилось, что итоговый список невозможно получить с сортировкой по цене - параметр orderByPrice , если его поместить в массив $params, не попадает в query string, а идет в тело JSON запроса, где не обрабатывается Маркетом. Думаю, что нужно добавить третий необязательный параметр $query_params для подобных случаев.

Для тех у кого аналогичная проблема - на текущий момент без изменения кода задача может быть решена передачей параметра прямо в regionId, то есть вызов метода делать как-то так: 
$modelClient->getModelsOffers('213&orderByPrice=ASC', ['models' => $modelsIdxs]);

**Comment by VitaliaSmaglenko** [comment]
Исправлено в pr #14
