### ISSUE TITLE
Service responded with error code: "400" and message: "Missing request parameter: regionId"

### ISSUE THREAD

**Issue by roker777** [yandex-market/yandex-market-php-partner#3]
Добрый день. Использую объект класса `\Yandex\Market\Partner\Clients\ModelClient` что бы вызвать метод `getModelsOffers()` и получить список предложений по модели, в ответ получаю ошибку  

> Service responded with error code: "400" and message: "Missing request parameter: regionId"

В документации к [библиотеке](https://github.com/yandex-market/yandex-market-php-partner/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D1%8B#%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D0%BF%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B9-%D0%B4%D0%BB%D1%8F-%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%B8%D1%85-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B5%D0%B9) указано, что этот параметр передается в массиве вместе с models, но в самой документации к [api](https://tech.yandex.ru/market/partner/doc/dg/reference/post-models-offers-docpage/) regionId передается как get параметр. 

Если передать его как get параметр, то запрос выполнится корректно

**Comment by MarketLLC** [comment]
Здравствуйте! regionId должен передаваться вторым параметром как массив, тогда строка запроса будет конкатенирована с идентификатором региона. Т.е. выглядеть будет приблизительно так:
$client->getModelOffers(1, ['regionId' => 20]);
Т.е. в любом случае regionId будет в GET-запросе.

**Comment by roker777** [comment]
> Здравствуйте! regionId должен передаваться вторым параметром как массив, тогда строка запроса будет конкатенирована с идентификатором региона. Т.е. выглядеть будет приблизительно так:
> $client->getModelOffers(1, ['regionId' => 20]);
> Т.е. в любом случае regionId будет в GET-запросе.

Добрый день. Мы ведем речь о разных методах. Вы привели пример для `getModelOffers - Список предложений для модели`, я де говорю про `getModelsOffers() - Список предложений для нескольких моделей`, в которой get параметр не формируется, но, по существу, требуется

**Comment by MarketLLC** [comment]
@roker777, Здравствуйте! Действительно обнаружили проблему, которую вы описывали выше. Спасибо большое за issue, поправили - сейчас всё должно работать корректно.
